# Cloud Build pipeline to build the server Docker image and deploy to Cloud Run.
# Usage: gcloud builds submit --config=cloudbuild.yaml .
# Substitutions expected: _REGION (e.g. us-central1), _SERVICE (optional), _API_KEY (if you want Cloud Build to set an env var)

# Provide top-level substitution defaults so Cloud Build recognizes the custom
# substitution variables when they are passed via --substitutions.

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/trade-mate-pro-backend:latest', # Your target image name
      '-f', 'server/Dockerfile', # Path to your Dockerfile relative to the repository root
      './server' # The build context, also relative to the repository root
    ]

images:
  - 'gcr.io/$PROJECT_ID/trade-mate-backend:latest'

timeout: 1200s
